name: Build and Deploy Cumulonimbus Production

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - name: Remove Stale Build Artifacts
        run: |
          rm -rf /www-data/dist
          rm -rf /www-data/domain-specific-pages
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Copy Static Build Artifacts
        run: |
          cp -R nginx/ /var/www-data
          cp -R domain-specific-pages/ /var/www-data
      - name: Install Dependencies
        run: yarn
      - name: Build Production
        run: yarn build-prod
      - name: Copy Build Artifacts
        run: cp -R dist/ /var/www-data
